### ISSUE TITLE
1.	The SBR Controls tab offers a box to enter the number of Mini-CAS pumps. 

### ISSUE THREAD

**Issue by chukon** [AquaAerobicSystemsInc/APD-Top-APD-Quick-Wins#1]
1.	The SBR Controls tab offers a box to enter the number of Mini-CAS pumps.  Entering in the number of MiniCAS pumps does not add anything to the BOM.  It should pull in part #2701508 and the quantity should be set to match the quantity entered in the box. 

![image](https://user-images.githubusercontent.com/3256516/42770799-d94fc11c-88ea-11e8-91a1-9a2609a008c7.png)

**Comment by chukon** [comment]
@phstanek the below code should add needed part to control panel for Mini-Cas > 0 (See code & image) 

            'Add  Mini-CAS pumps
            If MiniCas > 0 Then
                AddLevel3SubPartToDesign(DesignID, intNewGroupID, "2701508", CDec(MiniCas), 0)

            End If

![image](https://user-images.githubusercontent.com/3256516/43598257-e13cb2a6-9649-11e8-8f8e-1950a8442f27.png)

**Comment by chukon** [comment]
@phstanek Update: Need to add before Labor & Costing Section
----
      'Code
      'Add  Mini-CAS pumps
            If MiniCas > 0 Then
                AddLevel3SubPartToDesign(DesignID, intNewGroupID, "2701508", CDec(MiniCas), 0)
            End If
             
---
![image](https://user-images.githubusercontent.com/3256516/43600151-738c4b1c-964f-11e8-99cb-52eb332e0b65.png)

**Comment by phstanek** [comment]
Updated checked in and ready to publish to APD Development for testing.

**Comment by phstanek** [comment]
We tested this issue with Mark Hughes and it is confirmed to now populate the BOM and save the setting to the database.  It has been published to APD Live.
