### ISSUE TITLE
10.	The note for redundancy on the AquaPrime Design summary

### ISSUE THREAD

**Issue by chukon** [AquaAerobicSystemsInc/APD-Top-APD-Quick-Wins#10]
![image](https://user-images.githubusercontent.com/3256516/42771220-1265a4b6-88ec-11e8-8c01-a13657b55841.png)

**Comment by phstanek** [comment]
I spoke with Mark Hughes on this issue and we were unable to duplicate it.  I will place this issue on hold for now in case it arises again and more details can be obtained.

**Comment by phstanek** [comment]
I am closing this issue for now as we are unable to duplicate it.   It can be re-opened in the future if necessary.
