### ISSUE TITLE
11.	The influent turbidity value is off center from the other values. 

### ISSUE THREAD

**Issue by chukon** [AquaAerobicSystemsInc/APD-Top-APD-Quick-Wins#11]
![image](https://user-images.githubusercontent.com/3256516/42771241-2113f472-88ec-11e8-9805-8f8851e0c5e8.png)

**Comment by phstanek** [comment]
This is ready to be tested on the live system.

Report SBRPrelimPkg1MAINPrimeNEW.rpt has been updated.

**Comment by phstanek** [comment]
I tested this issue with Jakob Nowicki, and the updated report is now in the Live APD system.

Note that (2) report files had to be updated:
**SBRPrelimPkg1MAINPrimeNEW.rpt** - Used by the system when the SBR Prelim Package is selected
**SBRPrelimPkg1MAINPrimeCoverNEW.rpt** - Used by the system when the Design Cover Sheet for AquaPrime is selected (which then also selects the SBR Prelim Package)

**Comment by phstanek** [comment]
This issue has been resolved and can now be closed.
