### ISSUE TITLE
2.	Design note #460 states that “AquaNereda is a propriety technology”.  Propriety should be actually be proprietary. 

### ISSUE THREAD

**Issue by chukon** [AquaAerobicSystemsInc/APD-Top-APD-Quick-Wins#2]
![image](https://user-images.githubusercontent.com/3256516/42770868-fabb8f3e-88ea-11e8-9d19-55d0c84900c5.png)

**Comment by phstanek** [comment]
This issue is ready for test in the live system.

In table tbl000MasterListDesignNotes, the Note on NoteID 460 has been updated to change "propriety" to "proprietary".

**Comment by mhughes1** [comment]
Looks good!

**Comment by phstanek** [comment]
This issue has been resolved and can now be closed.
