### ISSUE TITLE
27.  Incident Report Combination/Sorting

### ISSUE THREAD

**Issue by phstanek** [AquaAerobicSystemsInc/APD-Top-APD-Quick-Wins#27]
Each week, we review the two incident reports circled below at the incident meeting. 
 
![image](https://user-images.githubusercontent.com/41307105/45978662-8221d600-c012-11e8-80d2-db5b6f03c7bb.png)

It would be more efficient for us if these two reports were combined into one.  It would also be good if we could sort the list by the project name, problem type, assigned department, assigned employee, or date reported fields from the Incident Log screen. 

 
![image](https://user-images.githubusercontent.com/41307105/45978695-91a11f00-c012-11e8-8059-78b8d376b39d.png)

Can this change be added to the APD to do list?   

Thanks,

Mark P. Hughes, P.E.
Product Manager - Filtration

**Comment by phstanek** [comment]
In reviewing the existing reports, I have found (2) potential problems to be corrected:

1. In the first report, possible incident exclusion in the summary sub-report may occur due to inconsistency in project type filtering.
2. In the summary sub-reports on both reports, the calculation for _Average Days Elapsed_ does not take into consideration that multiple incidents may exist on the same project, resulting in possible overstatement of the average (it uses the number of unique project numbers, not the number of incidents).  

Additionally, the "Total Number of Projects" in the sub-reports is actually the number of incidents, and I recommend changing it to "Total Number of Incidents" accordingly.

**Comment by phstanek** [comment]
An additional problem was found which was causing exclusion of 2 project types in the main report (_Membrane-Ceramic_ and _Membrane-Polymeric_).

I have created (3) new reports which address all issues found (2 new versions of the existing reports, plus the new combined report).  The new combined report is sorted based on criteria supplied by the user via a drop-down menu:
![image](https://user-images.githubusercontent.com/41307105/46106521-8e3a9e80-c19e-11e8-8ae8-0a152f05bdeb.png)

**Comment by phstanek** [comment]
After discussing with Mark, I will also add the flexibility to sort the Summary sub-report, as well as the ability to choose Ascending or Descending sorts for each.

**Comment by phstanek** [comment]
The menu and report have been updated to allow additional sort options:
![image](https://user-images.githubusercontent.com/41307105/46164506-c3ed8f00-c253-11e8-933d-46cbfff6d780.png)

This update has been published to APD Development and is now ready to be tested.

Test Plan:
[Test Plan for APD-Top-APD-Quick-Wins_Issue 027 - Incident Report Combination and Sorting.docx](https://github.com/AquaAerobicSystemsInc/APD-Top-APD-Quick-Wins/files/2425259/Test.Plan.for.APD-Top-APD-Quick-Wins_Issue.027.-.Incident.Report.Combination.and.Sorting.docx)

**Comment by mhughes1** [comment]
Completed testing.  Looks good! 

[Test Plan for APD-Top-APD-Quick-Wins_Issue 027 - Incident Report Combination and Sorting (002).docx](https://github.com/AquaAerobicSystemsInc/APD-Top-APD-Quick-Wins/files/2496562/Test.Plan.for.APD-Top-APD-Quick-Wins_Issue.027.-.Incident.Report.Combination.and.Sorting.002.docx)

**Comment by phstanek** [comment]
No issues found during testing - this update is scheduled for release Wednesday morning, 10/24/18.

**Comment by phstanek** [comment]
Per request, the new report (IncidentAllOpenAllDeptsAllProducts.rpt) now does not filter by department (it previously only included Electrical/Mechanical), and the launch button label has been updated accordingly.

The update has been published to APD Development.

**Comment by mhughes1** [comment]
Tested and works great!

**Comment by phstanek** [comment]
This update has been released to APD Live 11/7/18.
