### ISSUE TITLE
3.	Design note #175

### ISSUE THREAD

**Issue by chukon** [AquaAerobicSystemsInc/APD-Top-APD-Quick-Wins#3]
3.	Design note #175 reads “Provisions should be made for a post-equalization basin overflow. (by others)”  This note should be updated to read “Provisions should be made by others for a post-equalization basin overflow.”

![image](https://user-images.githubusercontent.com/3256516/42770912-25a3d4ae-88eb-11e8-9613-258301bfec60.png)

**Comment by mhughes1** [comment]
Looks good to me!

**Comment by phstanek** [comment]
This issue has been resolved and can now be closed.
