### ISSUE TITLE
4.	The redundancy note that pulls in with the SBR prelim package has the incorrect units for the metric maximum design flow. 

### ISSUE THREAD

**Issue by chukon** [AquaAerobicSystemsInc/APD-Top-APD-Quick-Wins#4]
4.	The redundancy note that pulls in with the SBR prelim package has the incorrect units for the metric maximum design flow. The Filter Summary report works correctly. This applies to the five possible redundancy conditions listed.

![image](https://user-images.githubusercontent.com/3256516/42771001-5d39bd7a-88eb-11e8-9ef6-90d5d1c05865.png)

**Comment by phstanek** [comment]
I worked with Mark Hughes today and we were able to duplicate this issue on the SBR Prelim Combined Package Report.

**Comment by phstanek** [comment]
The following (2) reports have been updated, and will be uploaded to APD Live when testing is about to commence:
SBRPrelimCombinedPkg1PRIME.rpt
SBRPrelimCombinedPkg1MAIN.rpt

A formal test plan has been written to cover all (19) conditions that need to be tested:
[Test Plan for APD Issue 4.docx](https://github.com/AquaAerobicSystemsInc/APD-Top-APD-Quick-Wins/files/2242789/Test.Plan.for.APD.Issue.4.docx)

**Comment by phstanek** [comment]
After discussion with Mark H., I have revised the test plan to remove ABF and Drum conditions.

Here is the updated test plan:
[Test Plan for APD Issue 4.docx](https://github.com/AquaAerobicSystemsInc/APD-Top-APD-Quick-Wins/files/2306536/Test.Plan.for.APD.Issue.4.docx)

**Comment by phstanek** [comment]
After analyzing reports for the PF-14/UFS-9 project, it was found that (3) additional reports also contained incorrect units.  I have modified these additional reports and incorporated them into a revised test plan.  I also re-worked the testing sequence for efficiency:

[Test Plan for APD Issue 4 Rev 1.docx](https://github.com/AquaAerobicSystemsInc/APD-Top-APD-Quick-Wins/files/2316084/Test.Plan.for.APD.Issue.4.Rev.1.docx)

**Comment by phstanek** [comment]
**Test Results Summary:**  The redundancy notes are displaying correctly, and this issue will now be closed.  No additional release to APD Live is required, as this was a report-only update and is thus already active in APD Live.
However, review of the reports during testing revealed two separate issues:
1.	Several reports are listing hydraulic loading rates at the average and max flow in l/s/m2, which should be updated for consistency.  A new APD Quick Wins issue will be generated to address this.
2.	The Length Per Diamond is being displayed as “0 ft”.  A new APD Quick Wins issue will be generated to address this as well.

[Test Plan for APD Issue 4 Rev 1_COMPLETED.docx](https://github.com/AquaAerobicSystemsInc/APD-Top-APD-Quick-Wins/files/2397847/Test.Plan.for.APD.Issue.4.Rev.1_COMPLETED.docx)
