### ISSUE TITLE
5.	With a four basin SBR system, the recommended quantity of air control valves is 4, but should be 7. 

### ISSUE THREAD

**Issue by chukon** [AquaAerobicSystemsInc/APD-Top-APD-Quick-Wins#5]
![image](https://user-images.githubusercontent.com/3256516/42771021-70f4281e-88eb-11e8-8304-3625ac5088f0.png)

**Comment by phstanek** [comment]
APD changes submitted and are ready for review/publishing to APD Development.

**Comment by phstanek** [comment]
This issue is ready to be tested in APD Live.

**Comment by phstanek** [comment]
I have tested this with Jakob Nowicki and it appears to be functioning properly in APD Live.

**Comment by phstanek** [comment]
This issue has been resolved and can now be closed.
