### ISSUE TITLE
6.	The AquaPrime Influent Tab does not include a Pre-Filter Treatment dropdown list that is on the Cloth Media Filter Influent tab.  This field populates a pre-filter treatment field on the design report, so it needs to be added to the AquaPrime influent tab.  The options can remain the same on both tabs.

### ISSUE THREAD

**Issue by chukon** [AquaAerobicSystemsInc/APD-Top-APD-Quick-Wins#6]
![image](https://user-images.githubusercontent.com/3256516/42771075-9d334068-88eb-11e8-9e81-aa0614b23c8b.png)

**Comment by phstanek** [comment]
APD changes submitted and are ready for review/publishing to APD Development.

The dropdown has been incorporated into the AquaPrime Influent tab, and it successfully reads from/writes to the database.  The next development step will be to populate the report.

**Comment by phstanek** [comment]
The AquaPrime design report has been updated, but will **not** be released to Live APD until the code has been published and tested as it would populate all reports with the default Prior Treatment value of "None" without giving users an interface in which to change it.

The following (2) report files have been updated:
SBRPrelimPkg1MAINPrimeNEW.rpt
SBRPrelimPkg1MAINPrimeCoverNEW.rpt

**Comment by phstanek** [comment]
I have tested this issue with Jakob Nowicki and it appears to be functioning properly in APD Live.

The following (2) reports were updated:
SBRPrelimPkg1MAINPrimeNEW.rpt
SBRPrelimPkg1MAINPrimeCoverNEW.rpt

**Comment by phstanek** [comment]
This issue has been resolved and can now be closed.
