### ISSUE TITLE
7.	Design note #255 starts with a “:” this needs to be removed. 

### ISSUE THREAD

**Issue by chukon** [AquaAerobicSystemsInc/APD-Top-APD-Quick-Wins#7]
![image](https://user-images.githubusercontent.com/3256516/42771101-b2032d8c-88eb-11e8-941b-6505910308b1.png)

**Comment by phstanek** [comment]
This issue is ready to test in the live system.

In table tbl000MasterListDesignNotes, the Note field in NoteID 255 was edited to remove the ":" and the space before the dash.

**Comment by mhughes1** [comment]
Looks good!

**Comment by phstanek** [comment]
This issue has been resolved and can now be closed.
